### ISSUE TITLE
why server players list are broke

### ISSUE THREAD

**Issue by mayersgamer** [Source2ZE/ServerListPlayersFix#1]
only counting players up but once they leave the server still counting them which leads to server going full even tho its empty , and nobody can join .

**Comment by Poggicek** [comment]
that's a cs2 bug, this plugin has nothing to do with it

**Comment by mayersgamer** [comment]
is there a fix for it ? im seeing some servers found a fix but cant find something about it , good job anyway now gamebrowser is showing players online and players that left too but still counted 👯

**Comment by Vauff** [comment]
There's [another plugin](https://github.com/Source2ZE/AuthSessionFix) that fixes that bug.
