### ISSUE TITLE
cs2 update today broke this

### ISSUE THREAD

**Issue by y3request** [Source2ZE/ServerListPlayersFix#2]
The cs2 update today April 30th/May 1st broke this plugin. It loads in meta mod fine, but it does not display players on the list.
I really love this plugin, thanks for making it.

**Comment by xen-000** [comment]
It needs a rebuild for the updated sdk

**Comment by unde4induser** [comment]
agree, can u fix?

**Comment by y3request** [comment]
There is a new release, https://github.com/Source2ZE/ServerListPlayersFix/releases/tag/v1.0.1

it is fixed so i am closing thread. thank you very much!
