### ISSUE TITLE
Lag! not working with latest cs2 updates

### ISSUE THREAD

**Issue by fuzzyscn** [Source2ZE/ServerListPlayersFix#5]
not working with latest cs2 updates
make win server lag to long!

**Comment by unde4induser** [comment]
on linux not working too, pls fix

**Comment by fuzzyscn** [comment]
> on linux not working too, pls fix

https://github.com/stefanx111/ServerListPlayersFix/actions/runs/9231524606/artifacts/1536692075
he has fixed

**Comment by unde4induser** [comment]
> > on linux not working too, pls fix
> 
> https://github.com/stefanx111/ServerListPlayersFix/actions/runs/9231524606/artifacts/1536692075 he has fixed

Ty, u a the best!!!!!!!!!!!!

**Comment by RiisDev** [comment]
Not working on Windows servers!

**Comment by fuzzyscn** [comment]
> 无法在 Windows 服务器上运行！
win 
https://github.com/stefanx111/ServerListPlayersFix/actions/runs/9231524606/artifacts/1536691895
